### ISSUE TITLE
SessionResult response deserialization issues

### ISSUE THREAD

**Issue by leonbotros** [tweedegolf/irmars#1]
https://github.com/tweedegolf/irmars/blob/659859d6aa2bdda636ee0672ca9011e74d3ecff1/src/sessionresult.rs#L71

This should be renamed using `#[serde(rename = "id")]`.

Other than that, it might be nicer to wrap the whole "disclosed" field in an option.

**Comment by leonbotros** [comment]
As side-effect, retrieving the result from a session that has completed succesfully will result in a `NetworkError` instead of a `SessionResult` (because deserialization fails).

**Comment by leonbotros** [comment]
Regarding making the "disclosed" field optional: Polling a session for a result that has not yet finished will (I think) also fail in a `NetworkError` because the field "disclosed" cannot be found.

**Comment by leonbotros** [comment]
Also, renaming `NetworkError` to something like `ReqwestError` would make more sense.

**Comment by leonbotros** [comment]
Closed by accident

**Comment by davidv1992** [comment]
Issue is fixed in master, will be released as part of 0.2.0
