### ISSUE TITLE
Use serde(rename_all)

### ISSUE THREAD

**Issue by leonbotros** [tweedegolf/irmars#2]
https://github.com/tweedegolf/irmars/blob/659859d6aa2bdda636ee0672ca9011e74d3ecff1/src/sessionresult.rs#L8

Just a suggestion but these definitions can all use `rename_all` as shown in serde docs here: https://serde.rs/container-attrs.html#rename_all, e.g., with "SCREAMING_SNAKE_CASE" for most and "lowercase/camelCase" for `SessionType`. This saves 15 lines in total.

**Comment by davidv1992** [comment]
Done in master
