### ISSUE TITLE
Give more information about the status of a session

### ISSUE THREAD

**Issue by leonbotros** [tweedegolf/irmars#3]
https://github.com/tweedegolf/irmars/blob/659859d6aa2bdda636ee0672ca9011e74d3ecff1/src/error.rs#L15
https://github.com/tweedegolf/irmars/blob/659859d6aa2bdda636ee0672ca9011e74d3ecff1/src/irmaclient.rs#L141

Feature suggestion:
Maybe this error variant could wrap the `SessionStatus`? This way users of `client.request()` can know not just that the session is not yet complete but also in which state it is.

**Comment by davidv1992** [comment]
Fixed in master
